service: integrate

package:
  individually: true  # Create an optimized package for our functions

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  logRetentionInDays: 14
  environment:
    serviceName: ${self:service}
    stage: ${self:custom.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  exchange-code:
    handler: exchange-code.handler
    events:
      - http:
          path: exchange-code
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action: ssm:GetParameters
        Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/${self:service}/${self:custom.stage}/*
