service: integrate

package:
  individually: true  # Create an optimized package for our functions

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  logRetentionInDays: 14

functions:
  exchange-code:
    handler: exchange-code.handler
    events:
      - http:
          path: exchange-code
          method: post
